apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: simple-postgres-deploy
  labels:
    app: postgres
data:
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_ADMIN: ${{ secrets.POSTGRES_ADMIN }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
